serenity.project.name=SWAG LABS
serenity.test.root=oren.example
webdriver.driver=firefox
webdriver.autodownload=true
serenity.browser.maximized=true
serenity.use.unique.browser=false
serenity.restart.browser.each.scenario=true

# Tiempos de espera agregados para Jenkins
webdriver.timeouts.implicitlywait=15000
webdriver.wait.for.timeout=15000

# Configuración Headless para Jenkins (Sin interfaz gráfica)
serenity.headless.mode=true
webdriver.firefox.arguments=-headless
