serenity.project.name=SWAG LABS
serenity.test.root=oren.example
webdriver.driver=firefox
webdriver.autodownload=true
serenity.browser.maximized=true
serenity.use.unique.browser=false
serenity.restart.browser.each.scenario=true
webdriver.timeouts.implicitlywait=15000
webdriver.wait.for.timeout=15000
firefox.preferences=browser.safebrowsing.enabled=false
headless.mode=true
