# Configuración original del proyecto
serenity.project.name=SWAG LABS
serenity.test.root=oren.example
webdriver.driver=firefox
webdriver.autodownload=true
serenity.browser.maximized=true
serenity.use.unique.browser=false
serenity.restart.browser.each.scenario=true

# Tiempos de espera aumentados para Jenkins
webdriver.timeouts.implicitlywait=15000
webdriver.wait.for.timeout=15000

# Configuración Headless y Resolución de pantalla
serenity.headless.mode=true
webdriver.firefox.arguments=-headless,--window-size=1920,1080
serenity.browser.width=1920
serenity.browser.height=1080
